### PR TITLE
Updates to include working with API

### PR DESCRIPTION
**Pull request by cmolinan**
### Updates

- Creation of a new game using the API.
- Implementation of the "Refresh" button that will get all scores for the game, from the API (receiving data from the API and parsing the JSON).
- Implementation of the form "Submit" button that will save a score for the game (sending data to the API).
- Using of arrow functions instead of the function keyword.
- Using of async and await JavaScript features to consume the API.
- No styling is required.

### CODE REVIEW

**Review by Whoistolu — APPROVED** [review]
### Hi @cmolinan 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by cmolinan** [comment]
@Whoistolu Thanks !

**Review by alexander16108 — COMMENTED** [review]
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has been used previously for a task please create a new pr and submit your tasks

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by cmolinan** [comment]
@alexander16108, this was an unfortunate mistake

**Pull request merged**
